### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Shawn-fd** [miguelsvasco/gmc#2]
`
Traceback (most recent call last):
  File "/home/tang/git_src/gmc/gmc_code/unsupervised/main_unsupervised.py", line 14, in <module>
    from gmc_code.unsupervised.utils.general_utils import (
  File "/home/tang/git_src/gmc/gmc_code/unsupervised/utils/general_utils.py", line 4, in <module>
    from gmc_code.unsupervised.modules.trainers.dca_evaluation_trainer import DCAEvaluator
  File "/home/tang/git_src/gmc/gmc_code/unsupervised/modules/trainers/dca_evaluation_trainer.py", line 6, in <module>
    from gmc_code.DelaunayComponentAnalysis.schemes import (
ModuleNotFoundError: No module named 'gmc_code.DelaunayComponentAnalysis'
`

It looks like this file is not in the library:  "gmc_code.DelaunayComponentAnalysis"

**Comment by petrapoklukar** [comment]
Hi @Shawn-fd,

thanks for you message. By default Delaunay Component Analysis is not included in our code since this is not part of our contribution. Thus, you need to add it to your workspace youself by following the [instructions on the official repository](https://github.com/petrapoklukar/dca). Let us know if we can help with anything else!

Best, 
Petra & Miguel

**Comment by Htermotto** [comment]
Hi,

Just want to follow up on this. I tried installing the DCA library according to their instructions, but it appears as if you copy and paste the DCA folder into the DelaunayComponentAnalysis folder in your project? Is that correct? I was unable to get that to work and there is a lot of import resolution/hacking needed it seems.

Would it be possible to provide the complete code, at least in a branch, so that this is runnable "out of the box?"

An additional side note is that the voronoi library is missing a #include <sstream> header that prevents it from compiling as is.
